name: Java CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Verify the Java package
        run: 
          - cd /home/runner/work/sparkjava-war-example/sparkjava-war-example/target/
          - ls -lrt